services:
  # Ultra-Fast Combined Service
  - type: web
    name: kalnetworks-ultra-fast
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python render_deploy.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: RUN_MODE
        value: both
      - key: BUSINESS_NAME
        value: "KalNetworks – Printing & Business Solutions"
      - key: BUSINESS_EMAIL
        value: "gebeyatechnologies@gmail.com"
      - key: BUSINESS_PHONE
        value: "0965552595"
      - key: BUSINESS_ADDRESS
        value: "KalNetworks Business Center"
      - key: BUSINESS_USERNAME
        value: "@ABISSINIANJA"
    
    # Ultra-fast health checks
    healthCheckPath: /health
    
    # Auto-deploy with optimizations
    autoDeploy: true
    preDeployCommand: echo "🚀 Ultra-fast deployment starting..."
    
    # Performance optimizations
    numInstances: 1
